# Variável para o endereço da sua API local. 
# Verifique no seu terminal qual a porta HTTPS correta quando você roda o projeto (geralmente na faixa 7000).
@FinancialGoal.API_HostAddress = https://localhost:7243

# Requisição para simular um investimento
# Para executar: clique no pequeno botão verde "Send Request" que aparece acima desta linha.
POST {{FinancialGoal.API_HostAddress}}/simular
Content-Type: application/json

{
  "goalValue": 50000,
  "initialInvestment": 5000,
  "monthlyInvestment": 400,
  "goalDate": "2030-12-01"
}