@FinancialGoal.API_HostAddress = https://localhost:7243

# requisição para simular um investimento
POST {{FinancialGoal.API_HostAddress}}/simular
Content-Type: application/json

{
  "goalValue": 50000,
  "initialInvestment": 5000,
  "monthlyInvestment": 400,
  "goalDate": "2030-12-01"
}